# Copyright 2018 LG Electronics, Inc.

BBPATH ?= ""
# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"
# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILES += "${LAYERDIR}/${DISTRO}-only/recipes-*/*/*.bb ${LAYERDIR}/${DISTRO}-only/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-neva"
BBFILE_PATTERN_meta-neva := "^${LAYERDIR}/"
# The priority for a meta layer set in the conf/layer.conf overlaps the priority
# for the same meta layer set in the weboslayers.py file.
# It is better to keep them in sync, like it does for other meta layers.
BBFILE_PRIORITY_meta-neva = "99"

LAYERSERIES_COMPAT_meta-neva = "kirkstone scarthgap"

HOSTTOOLS:append = " curl pgrep"
HOSTTOOLS:append:webos = " python2.7"

# Use custom libc++ library from Chromium internals if toolchain is Clang
USE_WEBRUNTIME_LIBCXX = "${@oe.utils.conditional('WEBRUNTIME_TOOLCHAIN', '-clang', '1', '', d)}"
